# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/lightrag1',
                'doc_host': 'https://adamaslan.github.io',
                'git_url': 'https://github.com/adamaslan/lightrag1',
                'lib_path': 'lightrag1'},
  'syms': { 'lightrag1.cb2': { 'lightrag1.cb2.initialize_rag': ('cb2.html#initialize_rag', 'lightrag1/cb2.py'),
                               'lightrag1.cb2.load_or_compute_embeddings': ('cb2.html#load_or_compute_embeddings', 'lightrag1/cb2.py'),
                               'lightrag1.cb2.main': ('cb2.html#main', 'lightrag1/cb2.py'),
                               'lightrag1.cb2.print_query_metrics': ('cb2.html#print_query_metrics', 'lightrag1/cb2.py'),
                               'lightrag1.cb2.print_stream': ('cb2.html#print_stream', 'lightrag1/cb2.py')},
            'lightrag1.core': {'lightrag1.core.foo': ('core.html#foo', 'lightrag1/core.py')},
            'lightrag1.lightrag1': { 'lightrag1.lightrag1.initialize_rag': ('cb2.html#initialize_rag', 'lightrag1/lightrag1.py'),
                                     'lightrag1.lightrag1.main': ('cb2.html#main', 'lightrag1/lightrag1.py'),
                                     'lightrag1.lightrag1.print_query_metrics': ('cb2.html#print_query_metrics', 'lightrag1/lightrag1.py'),
                                     'lightrag1.lightrag1.print_stream': ('cb2.html#print_stream', 'lightrag1/lightrag1.py')}}}
