# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/lightrag1',
                'doc_host': 'https://adamaslan.github.io',
                'git_url': 'https://github.com/adamaslan/lightrag1',
                'lib_path': 'lightrag1'},
  'syms': {'lightrag1.core': {'lightrag1.core.foo': ('core.html#foo', 'lightrag1/core.py')}}}
