project:
  type: website

website:
  title: "My Quarto and Nbdev Website"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Analysis"
        href: nbs/cb2.ipynb

format:
  html:
    theme: cosmo
    code-fold: true
